package de.zonlykroks.advancedchemistry.items.enums;

public enum Type {

    NONMETAL,NOBLE_GAS,ALKALI_METAL,METALLOID,HALOGEN,TRANSITION_METAL,ALKALI_EARTH_METAL,METAL,LANTHANIDE,ACTINIDE,TRANSACTINIDE
}
